# ------------------------------
# general
# ------------------------------

set -g default-terminal 'tmux-256color'
set -g terminal-overrides ',xterm-256color:Tc'
set -as terminal-overrides ',xterm*:sitm=\E[3m'

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g mouse on
setw -g xterm-keys on

set -s escape-time 0
set -sg repeat-time 500  # key sequence timeout
set -s focus-events on

set -q -g status-utf8 on
setw -q -g utf8 on

set -g history-limit 1000

# vi mode
set -g status-keys vi
set -g mode-keys vi

# reload configuration
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'

# ------------------------------
# display
# ------------------------------

set -g base-index 1           # start window numbering at 1
setw -g pane-base-index 1     # make pane numbering consistent with window

set -g renumber-windows on    # renumber window when a window is closed
setw -g automatic-rename on   # rename window to reflect current program

set -g set-titles on          # set terminal title
#set -g set-titles-string '#W/#T'

set -g display-panes-time 800 # slightly longer pane indicators display time
set -g display-time 1000      # slightly longer status messages display time

set -g status-interval 10     # redraw status line every 10 seconds

bind -n C-l send-keys C-l \; clear-history  # clear screen and history

# quite mode
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# disable status line
#set -g status off

# move status line to top
#set -g status-position top

# ------------------------------
# navigation
# ------------------------------

# session
bind C-n new-session
bind C-q kill-session
bind C-f command-prompt -p find-session 'switch-client -t %%'  # find session
bind BTab switch-client -l  # move to last session
bind R refresh-client

# window
bind C-t new-window
bind C-w kill-window
bind C-d kill-pane

# window navigation
unbind n
unbind p
bind -r C-[ previous-window
bind -r C-] next-window

# split window
unbind '"'
unbind %
bind - split-window -v  # horizontally
bind \\ split-window -h  # vertical

# pane navigation
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -n M-Left select-pane -L  # move by alt (meta) & arrows
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -r [ swap-pane -U  # to previous pane
bind -r ] swap-pane -D  # to next pane

# pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# ------------------------------
# colorscheme
# ------------------------------

# terminal title
set -g set-titles-string '#(whoami)@#H ❐ #S ┃ #I:#W'

# default bar
set-option -g status-style bg='#1b1c36',fg='#ecf0c1'

# active pane
set -g pane-active-border-style 'fg=#5ccc96'

# inactive pane
set -g pane-border-style 'fg=#30365f'

# active window
set-option -g window-status-current-style fg='#ecf0c1'
set -g window-status-current-format ' [#I:#W] '

# inactive window
set-option -g window-status-style fg='#30365f'
set -g window-status-format ' #I:#W '

# message
set-option -g message-style bg='#30365f',fg='#ecf0c1'
set-option -g message-command-style bg='#30365f',fg='#ecf0c1'

# when commands are run
set -g message-style bg='#30365f',fg='#0f111b'

# Set left side status bar length and style
set -g status-left-length 100
set -g status-left-style default

# Display the session name
set -g status-left '#[bg=#7a5ccc] ❐ #S #[default]'

# Set right side status bar length and style
set -g status-right-length 100
set -g status-right-style default

# Display the date
set -g status-right '#[fg=#ce6f8f] %a %m/%d #[default]'

# Display the time
set -ag status-right '#[fg=#e39400] %I:%M %p #[default]'
