# --------------------------------
# config
# --------------------------------

font_family         Jetbrains Mono
bold_font           Jetbrains Mono
italic_font         Jetbrains Mono
bold_italic_font    Jetbrains Mono
font_size           10.5

shell_integration       no-cursor
cursor_shape            block
cursor_blink_interval   0

scrollback_lines    1000

strip_trailing_spaces   smart

sync_to_monitor     yes

enable_audio_bell   no

remember_window_size    no

enable_layouts  splits,stack

window_padding_width    5

inactive_text_alpha     1.0

hide_window_decorations no

tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted

allow_remote_control    yes

term    xterm-256color

# --------------------------------
# keymap
# --------------------------------

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+\ launch --location=vsplit
map ctrl+- launch --location=hsplit
map ctrl+alt+\ launch --cwd=current --location=vsplit --copy-env
map ctrl+alt+- launch --cwd=current --location=hsplit --copy-env

map ctrl+] next_window
map ctrl+[ previous_window
map ctrl+shift+] move_window_forward
map ctrl+shift+[ move_window_backward
map ctrl+shift+\ move_window_to_top

map ctrl+> next_tab
map ctrl+< previous_tab
map ctrl+shift+t new_tab
map ctrl+shift+q close_tab

map ctrl+shift+` next_layout

# --------------------------------
# colorscheme
# --------------------------------

# spaceduck
background #0f111b
foreground #ecf0c1
cursor #ecf0c1
selection_background #686f9a
color0 #000000
color8 #686f9a
color1 #e33400
color9 #e33400
color2 #5ccc96
color10 #5ccc96
color3 #b3a1e6
color11 #b3a1e6
color4 #00a3cc
color12 #00a3cc
color5 #f2ce00
color13 #f2ce00
color6 #7a5ccc
color14 #7a5ccc
color7 #686f9a
color15 #f0f1ce
selection_foreground #ffffff
