apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs
  namespace: default
spec:
  chart: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  targetNamespace: default
  valuesContent: |-
    nfs:
      server: {{ip_addr}}
      path: {{export_dir}}
      mountOptions:
        - nfsvers=4
    storageClass:
      name: nfs
      reclaimPolicy: Retain
