#! /bin/sh

sxhkd &

polybar main &

dunst &

feh --bg-center ~/.config/wall.png &

setxkbmap -option ctrl:nocaps &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config focused_border_color "#F0F5F9"
bspc config normal_border_color	 "#1E2022"

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding			 0
