#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom --experimental-backends &

polybar --reload main &

dunst &

pactl set-sink-mute 0 toggle &

ibus-daemon -drx &

feh --bg-fill ~/.config/wallpapers/wave.png &

setxkbmap -option ctrl:nocaps &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config focused_border_color "#a9b1d6"
bspc config normal_border_color  "#1f2335"

bspc config border_width         3
bspc config window_gap           3

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          0
