#! /bin/sh

sxhkd &

#polybar main &
sh ~/.config/polybar/launch.sh &

#picom &

dunst &

amixer -q sset Master 0 &

ibus-daemon -drx &

feh --bg-fill ~/.config/wall.jpg &

setxkbmap -option ctrl:nocaps &

bspc monitor -d ichi ni san shi go roku

bspc config focused_border_color "#a89984"
bspc config normal_border_color	 "#282828"

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding			 0
