[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#000000"
foreground = "#f8f8f0"

# # Normal colors
# [colors.normal]
# black     = '0x000000'
# red       = '0xff5f59'
# green     = '0x44bc44'
# yellow    = '0xd0bc00'
# blue      = '0x2fafff'
# magenta   = '0xfeacd0'
# cyan      = '0x00d3d0'
# white     = '0xf8f8f0'

# # Bright colors
# [colors.bright]
# black     = '0x1e1e1e'
# red       = '0xff5f5f'
# green     = '0x44df44'
# yellow    = '0xefef00'
# blue      = '0x338fff'
# magenta   = '0xff66ff'
# cyan      = '0x00eff0'
# white     = '0x989898'

# [[colors.indexed_colors]]
# index     = 16
# color     = '0xfec43f'

# [[colors.indexed_colors]]
# index     = 17
# color     = '0xff9580'

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 9.5

[font.bold]
family = "Maple Mono NF CN"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF CN"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Maple Mono NF CN"
style = "Italic"

[font.normal]
family = "Maple Mono NF CN"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001B[68;5u"
key = "D"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[73;5u"
key = "I"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[74;5u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;5u"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[80;5u"
key = "P"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[81;5u"
key = "Q"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[83;5u"
key = "S"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[84;5u"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Terminal"

[window.padding]
x = 5
y = 5
