type = internal/date
interval = 5

date =
date-alt = " %a, %m/%d/%Y"

time = " %I:%M %p"
time-alt =

;format-prefix = 

format-background = #1E2022
format-foreground = #F0F5F9

label = %date%%time%
label-padding = 1
