type = internal/pulseaudio

label-volume = " %percentage%%"
label-volume-background = #1E2022
label-volume-foreground = #F0F5F9
label-volume-padding = 1
label-muted = " muted"
;label-muted-background = #CC6666
label-muted-padding = 1
